# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
#
require:
  - rubocop-rake
  # - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - gemfiles/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/FileName:
  Exclude:
    - lib/flatware-*.rb
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
Gemspec/RequiredRubyVersion:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false
  Severity: warning
